Add typescript definition
mifi/react-lottie-player pull request #23
Opened 2021-03-04 11:03 UTC by skoruba

This PR added the typescript definition which was descibed in this issue #5.

2021-03-25 09:44 UTC, mifi commented
Hi!
Have you confirmed that microbundle will include the typedefinitions in the dist directory after building? Did you mange to solve the issue that his guy had in #9 ?

2021-04-29 16:47 UTC, jamiehaywood commented on package.json
> +  "types": "src/types/index.d.ts",
you'll probably need to add this for it to work in the bundling

```suggestion
  "types": "dist/index.d.ts",
  "engines": {
    "node": ">=10"
  },
  "scripts": {
    "build": "microbundle-crl --no-compress --format modern,cjs && cp src/types/index.d.ts /dist",
    "start": "microbundle-crl watch --no-compress --format modern,cjs",
```

2021-04-29 16:50 UTC, jamiehaywood requested changes
you'll need to add to the end of the `build` script:
`&& cp src/types/index.d.ts dist` (I've not tested this, so check it works)

you'll also need to change the types location to `dist/index.d.ts`

All of this depends on the @mifi 's choice of folder/file structure.

2021-04-30 05:41 UTC, mifi commented
that sounds good to me. maybe we should merge the types from this PR with the types from https://github.com/mifi/react-lottie-player/pull/9/files

I see it has some potentially better types like `direction?: 1 | -1` and `animationData: object`

2021-04-30 09:14 UTC, jamiehaywood commented
I think we merge them & then re-review, because there are a few types that could be improved

2021-06-20 19:40 UTC, osmarpb97 commented
Any update?

2021-06-21 06:22 UTC, mifi commented
I don't have the TS expertise, but if someone wants to test, verify and vouch for a TS PR, then I'm happy to merge!

2021-06-21 11:09 UTC, jamiehaywood commented
@mifi I'm happy to get involved here and raise a PR cherry picking the best types from all 3 PRs.

2021-06-24 06:00 UTC, mifi commented
closing in favor of #32
if anyone has improvements to that, feel free to create a pr

2021-06-24 06:00 UTC, closed without merging